version=0.1
[default.package.parameters]
s3_bucket = "my-lambda-artifacts-ab-15121"
region = "us-east-1"
image_repository="888276918709.dkr.ecr.us-east-1.amazonaws.com/python-container-example"
[default.deploy.parameters]
s3_bucket = "my-lambda-artifacts-ab-15121"
region = "us-east-1"
image_repository="888276918709.dkr.ecr.us-east-1.amazonaws.com/python-container-example"