AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  InlineLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: "../"
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image